'use client'
import SectionEditor from '@/components/admin/SectionEditor'

const J = (v: unknown) => JSON.stringify(v)

const FIELDS = [
  { key: 'jyuzu_heading_about', label: '「数珠づくりとは」見出し', defaultValue: '数珠づくりとは', translatable: true },
  { key: 'jyuzu_about_p1', label: '数珠づくりとは（段落1）', multiline: true, defaultValue: '数珠（じゅず）は、仏様を礼拝するときに手に持つ法具です。当山の数珠づくり体験では、天然石・天然木の珠からご自由に組み合わせを選び、世界にひとつだけのオリジナル数珠（ブレスレット）をお作りいただけます。', translatable: true },
  { key: 'jyuzu_about_p2', label: '数珠づくりとは（段落2）', multiline: true, defaultValue: '職員が丁寧にご説明しますので、どなたでも簡単にお作りいただけます。僧侶がご祈祷したものを当日お守りとしてお持ち帰りいただけます。', translatable: true },
  { key: 'jyuzu_heading_course', label: '「コース説明」見出し', defaultValue: 'コース説明', translatable: true },
  { key: 'jyuzu_course_desc', label: 'コース説明 補足文', defaultValue: '天然石・天然木の組成は、コースごとに以下のようになります。', translatable: true },
  { key: 'jyuzu_heading_flow', label: '「体験の流れ」見出し', defaultValue: '体験の流れ', translatable: true },
  { key: 'jyuzu_heading_fees', label: '「開催日・料金」見出し', defaultValue: '開催日・料金', translatable: true },
  { key: 'jyuzu_days', label: '開催日', defaultValue: '毎日開催（法要時は中止となる場合があります）', translatable: true },
  { key: 'jyuzu_hours_summer', label: '体験時間（4月〜10月）', defaultValue: '4月〜10月：9:00〜15:00', translatable: true },
  { key: 'jyuzu_hours_winter', label: '体験時間（11月〜3月）', defaultValue: '11月〜3月：9:00〜14:00', translatable: true },
  { key: 'jyuzu_fee',  label: '体験料', defaultValue: '2,000円〜（使用素材により異なります）', translatable: true },
  { key: 'jyuzu_time', label: '所要時間', defaultValue: '30分〜1時間（個人差があります）', translatable: true },
  { key: 'jyuzu_capacity', label: '体験人数', defaultValue: '1名〜20名まで', translatable: true },
  { key: 'jyuzu_target', label: '対象', defaultValue: '小学生以上（小学生は保護者同伴）', translatable: true },
  { key: 'jyuzu_place', label: '受付場所', defaultValue: '大黒天堂窓口', translatable: true },
  { key: 'jyuzu_price_note_label', label: '料金補足の見出し', defaultValue: '料金について', translatable: true },
  { key: 'jyuzu_price_note', label: '料金についての補足', multiline: true, defaultValue: 'お選びいただく珠の素材・組み合わせによって料金が異なります。詳しくは下記コース説明をご覧ください。', translatable: true },
  { key: 'jyuzu_group_note_label', label: '団体案内の見出し', defaultValue: '団体のご案内', translatable: true },
  { key: 'jyuzu_group_note', label: '団体のご案内 補足', multiline: true, defaultValue: '数珠づくり体験、団体のご予約も承っております。20名様を超える場合は、ご相談ください。', translatable: true },
  {
    key: 'jyuzu_flow', label: '体験の流れ', type: 'list' as const,
    listFields: [{ key: 'title', label: 'ステップ名' }, { key: 'text', label: '説明', multiline: true }],
    defaultValue: J([
      { title: '好きな珠を選ぶ', text: '天然石・天然木をご自由に組み合わせてお選びいただけます。' },
      { title: '数珠を作る', text: 'スタッフが丁寧にサポートしますので、どなたでも簡単にお作りいただけます。' },
      { title: 'ご祈祷', text: '僧侶がご祈祷し、お守りとして当日お持ち帰りいただけます。' },
    ]),
    translatable: true,
    defaultValueEn: J([
      { title: 'Choose Your Beads', text: 'Freely combine natural stone and wood beads to your liking.' },
      { title: 'Make Your Bracelet', text: 'Our staff will guide you carefully, so anyone can make one easily.' },
      { title: 'Blessing', text: 'A priest will bless it, and you can take it home the same day as an omamori charm.' },
    ]),
  },
  {
    key: 'jyuzu_samples', label: 'サンプル（コース）', type: 'list' as const,
    listFields: [{ key: 'course', label: 'コース名' }, { key: 'price', label: '価格' }, { key: 'desc', label: 'キャッチコピー' }],
    defaultValue: J([
      { course: 'Aコース', price: '2,000円', desc: '天然木で作るスタンダードな数珠' },
      { course: 'Bコース', price: '4,000円', desc: '天然石と天然木の個性あふれる数珠' },
      { course: 'Cコース', price: '6,000円', desc: '天然石のみで作る特別な数珠' },
    ]),
    translatable: true,
    defaultValueEn: J([
      { course: 'Course A', price: '¥2,000', desc: 'A standard bracelet made of natural wood' },
      { course: 'Course B', price: '¥4,000', desc: 'A distinctive bracelet mixing natural stone and wood' },
      { course: 'Course C', price: '¥6,000', desc: 'A special bracelet made entirely of natural stone' },
    ]),
  },
  {
    key: 'jyuzu_materials', label: '珠の素材', type: 'list' as const,
    listFields: [{ key: 'name', label: '素材名' }, { key: 'desc', label: '説明', multiline: true }],
    defaultValue: J([
      { name: '天然木', desc: '軽くて使いやすい木の珠。温かみのある手触りが特徴です。' },
      { name: '天然石', desc: '色とりどりの天然石の珠。お好みの色でお選びいただけます。' },
    ]),
    translatable: true,
    defaultValueEn: J([
      { name: 'Natural Wood', desc: 'Lightweight, easy-to-wear wooden beads, known for their warm texture.' },
      { name: 'Natural Stone', desc: 'Colorful natural stone beads, available in your favorite colors.' },
    ]),
  },
  { key: 'jyuzu_heading_materials', label: '「選べる珠」見出し', defaultValue: '選べる珠', translatable: true },
  { key: 'jyuzu_materials_hint', label: '選べる珠 補足（タップ案内）', defaultValue: '珠をタップすると説明が表示されます', translatable: true },
  { key: 'jyuzu_materials_note', label: '選べる珠 注意書き', defaultValue: '珠の種類は季節・入荷状況により変わります。当日の受付窓口でご確認ください。', translatable: true },
  {
    key: 'jyuzu_stones', label: '選べる珠：天然石（写真は変更できません。並び順・追加削除すると写真がずれるため注意）', type: 'list' as const,
    listFields: [{ key: 'name', label: '石の名前' }, { key: 'desc', label: '説明', multiline: true }],
    defaultValue: J([
      { name: '水晶', desc: '浄化作用があり、邪気を払い、災難を防ぐとされる万能の石です。' },
      { name: '紅水晶', desc: '内面の美しさを輝かせるご利益があるとされています。' },
      { name: 'ラピスラズリ', desc: '知性・直観力を高め、幸運を引き寄せるとされています。' },
      { name: 'アメジスト', desc: 'マイナスエネルギーをプラスに導くご利益があるとされる紫の石です。' },
      { name: 'メノウ', desc: '健康や長寿、子宝をもたらすとされる石です。' },
      { name: 'ピンクタイガーアイ', desc: '仕事運・恋愛運・金運アップのご利益があるとされています。' },
      { name: 'ゴールドシルバータイガーアイ', desc: '視野を広げ、正しい判断と行動で成功へと導くとされています。' },
      { name: 'トラメ石', desc: '決断力・行動力を高めるとされる石です。' },
      { name: '赤トラメ石', desc: '幸運を招き、霊力を授けるとされる石です。' },
      { name: 'ライトブルータイガーアイ', desc: '冷静さや判断力を高めるとされるタイガーアイの一種です。' },
      { name: 'ミックスタイガーアイ', desc: '成功や勝利、チャンスをつかむご利益があるとされています。' },
      { name: 'パープルキャッツアイ', desc: '直感力を研ぎ澄まし、判断力を強めるとされる石です。' },
      { name: 'ピーチジェイド', desc: '心と体のバランスを整えるとされる石です。' },
      { name: '茶金石', desc: '精神を安定させ、心の疲れを癒すとされる石です。' },
      { name: '紫金石', desc: '善い人や物、チャンスとの出会いを導くとされる石です。' },
      { name: 'ハウライト', desc: '厄除け効果があり、精神の安定・浄化、意志を強くするとされています。' },
      { name: 'エンジェライト', desc: 'ネガティブな感情を浄化し、優しさと癒しをもたらすとされています。' },
      { name: 'カーネリアン', desc: '気力アップ・体を丈夫にし、迷いを断ち切るとされる石です。' },
      { name: 'オニキス', desc: '邪気祓い・厄除け・魔除けの効果があるとされる石です。' },
      { name: 'インド翡翠', desc: '失った気力を回復させ、強いパワーで物事を成し遂げるとされています。' },
      { name: 'プラムジェイド', desc: '気品と落ち着きをもたらすとされる、深みのある色合いの石です。' },
    ]),
    translatable: true,
    defaultValueEn: J([
      { name: 'Crystal', desc: 'An all-purpose stone said to purify, ward off negative energy, and prevent misfortune.' },
      { name: 'Rose Quartz', desc: 'Said to bring out inner beauty.' },
      { name: 'Lapis Lazuli', desc: 'Said to enhance intelligence and intuition, drawing good fortune.' },
      { name: 'Amethyst', desc: 'A purple stone said to turn negative energy into positive.' },
      { name: 'Agate', desc: 'Said to bring health, longevity, and blessings of children.' },
      { name: 'Pink Tiger Eye', desc: 'Said to boost career, romance, and financial fortune.' },
      { name: 'Gold Silver Tiger Eye', desc: 'Said to broaden perspective and lead to success through sound judgment and action.' },
      { name: 'Torame Stone', desc: 'Said to strengthen decisiveness and initiative.' },
      { name: 'Red Torame Stone', desc: 'Said to invite good fortune and bestow spiritual power.' },
      { name: 'Light Blue Tiger Eye', desc: 'A type of tiger eye said to enhance calmness and judgment.' },
      { name: 'Mixed Tiger Eye', desc: 'Said to bring success, victory, and the ability to seize opportunity.' },
      { name: 'Purple Cat\'s Eye', desc: 'Said to sharpen intuition and strengthen judgment.' },
      { name: 'Peach Jade', desc: 'Said to balance mind and body.' },
      { name: 'Bronzite', desc: 'Said to stabilize the spirit and heal mental fatigue.' },
      { name: 'Purple Sunstone', desc: 'Said to bring encounters with good people, things, and opportunities.' },
      { name: 'Howlite', desc: 'Said to ward off misfortune, stabilize and purify the spirit, and strengthen willpower.' },
      { name: 'Angelite', desc: 'Said to purify negative emotions and bring gentleness and healing.' },
      { name: 'Carnelian', desc: 'Said to boost vitality, strengthen the body, and cut through hesitation.' },
      { name: 'Onyx', desc: 'Said to ward off negative energy and misfortune.' },
      { name: 'Indian Jade', desc: 'Said to restore lost energy and accomplish tasks with strong power.' },
      { name: 'Plum Jade', desc: 'A deeply colored stone said to bring elegance and composure.' },
    ]),
  },
  {
    key: 'jyuzu_woods', label: '選べる珠：天然木（写真は変更できません。並び順・追加削除すると写真がずれるため注意）', type: 'list' as const,
    listFields: [{ key: 'name', label: '木の名前' }, { key: 'desc', label: '説明', multiline: true }],
    defaultValue: J([
      { name: 'けやき', desc: '古くから神木として親しまれ、成長・発展の象徴とされる木材です。' },
      { name: '黒檀', desc: '高級木材として知られ、魔除け・厄除けのご利益があるとされます。' },
      { name: '紫檀', desc: '気品ある紫色が特徴で、健康長寿のご利益があるとされています。' },
      { name: '星月菩提樹', desc: '表面の斑点が星と月に見えることからその名がつき、縁結びのご利益で知られます。' },
      { name: '梅', desc: '「梅は百花の魁」といわれ、開運・厄除けの木として親しまれています。' },
      { name: 'つげ', desc: '緻密で丈夫な木質が特徴で、印材にも使われる縁起の良い木材です。' },
      { name: '緑壇', desc: '爽やかな緑色が特徴で、癒やしと安らぎをもたらすとされています。' },
      { name: '鉄刀木', desc: '硬く丈夫な木質で知られ、魔除け・厄除けのご利益があるとされます。' },
      { name: 'シャム柿', desc: '縞模様が美しい銘木で、独特の風合いを楽しめる木材です。' },
      { name: '鉄刀木（ツヤ有）', desc: '艶やかに仕上げられた鉄刀木の珠。硬く丈夫な木質で、魔除け・厄除けのご利益があるとされます。' },
      { name: '梅（ツヤ有）', desc: '艶やかに仕上げられた梅の珠。「梅は百花の魁」といわれ、開運・厄除けの木として親しまれています。' },
      { name: 'つげ（ツヤ有）', desc: '艶やかに仕上げられたつげの珠。緻密で丈夫な木質が特徴で、印材にも使われる縁起の良い木材です。' },
      { name: '椰', desc: '椰子の実を使った、素朴な模様が魅力の木材です。' },
    ]),
    translatable: true,
    defaultValueEn: J([
      { name: 'Zelkova', desc: 'Long cherished as a sacred tree, symbolizing growth and development.' },
      { name: 'Ebony', desc: 'A prized luxury wood said to ward off evil and misfortune.' },
      { name: 'Rosewood', desc: 'Known for its elegant purple hue and blessings of health and longevity.' },
      { name: 'Bodhi Seed (Star & Moon)', desc: 'Named for surface spots resembling stars and the moon, known for blessings of good relationships.' },
      { name: 'Plum Wood', desc: 'Known as "the first of a hundred flowers," cherished as a tree of good fortune and warding off misfortune.' },
      { name: 'Boxwood', desc: 'A fine, durable wood also used for seals — an auspicious material.' },
      { name: 'Green Ebony', desc: 'Known for its refreshing green color, said to bring healing and peace.' },
      { name: 'Tagayasan', desc: 'A hard, durable wood said to ward off evil and misfortune.' },
      { name: 'Siamese Ebony', desc: 'A prized wood with beautiful striped grain and a distinctive texture.' },
      { name: 'Tagayasan (Polished)', desc: 'Polished tagayasan beads — a hard, durable wood said to ward off evil and misfortune.' },
      { name: 'Plum Wood (Polished)', desc: 'Polished plum wood beads — "the first of a hundred flowers," a tree of good fortune and warding off misfortune.' },
      { name: 'Boxwood (Polished)', desc: 'Polished boxwood beads — a fine, durable wood also used for seals, an auspicious material.' },
      { name: 'Coconut Wood', desc: 'Made from coconut shell, prized for its rustic, distinctive grain.' },
    ]),
  },
  { key: 'jyuzu_heading_notes', label: '「ご注意・持ち物」見出し', defaultValue: 'ご注意・持ち物', translatable: true },
  {
    key: 'jyuzu_notes', label: 'ご注意・持ち物', type: 'list' as const,
    listFields: [{ key: 'text', label: '項目', multiline: true }],
    defaultValue: J([
      { text: '数珠はすべてブレスレットタイプです。' },
      { text: '参拝料（拝観料）は別途お求めください。' },
      { text: '僧侶がご祈祷したものを当日お守りとしてお持ち帰りいただけます。僧侶が不在の場合、後日ご祈祷後郵送いたします（郵送料は当寺負担）。' },
      { text: '団体でお越しの際は事前にお電話ください。' },
    ]),
    translatable: true,
    defaultValueEn: J([
      { text: 'All bracelets are wrist-worn style.' },
      { text: 'Please pay the visiting admission fee separately.' },
      { text: 'A priest blesses your bracelet, which you take home the same day as an omamori charm. If no priest is available, it will be blessed later and mailed to you (postage covered by the temple).' },
      { text: 'For group visits, please call in advance.' },
    ]),
  },
  { key: 'jyuzu_cta_heading', label: 'CTA見出し', defaultValue: '数珠づくり体験のご予約', translatable: true },
  { key: 'jyuzu_cta_sub', label: '予約ボタン下の説明文', defaultValue: '毎日開催しております。団体でお越しの際は事前にお電話ください。', translatable: true },
  { key: 'jyuzu_heading_instagram', label: '「みなさんの投稿」見出し', defaultValue: 'みなさんの投稿', translatable: true },
  { key: 'jyuzu_instagram_hint', label: '「みなさんの投稿」補足文', multiline: true, defaultValue: '「#中禅寺立木観音」「#数珠づくり体験」のハッシュタグをつけて投稿すると、こちらでご紹介させていただくことがあります。', translatable: true },
  {
    key: 'jyuzu_instagram_urls', label: 'Instagram投稿URL一覧（掲載する投稿のURLを追加・削除できます）', type: 'list' as const,
    listFields: [{ key: 'url', label: 'Instagram投稿URL（例: https://www.instagram.com/p/xxxxxxxxxxx/）' }],
    defaultValue: '[]',
  },
] as const

export default function AdminChuzenjJyuzu() {
  return <SectionEditor title="数珠づくり体験" href="/experience/jyuzu" fields={FIELDS as never} />
}
